# Generated by Django 5.2.14 on 2026-05-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
